import { GRID_COLS, GRID_ROWS } from './constants.ts'
import type { LevelDefinition, Tile, TileKind, Vec } from './types.ts'

export const DEFAULT_LEVEL_ROWS = [
  '...B.B.B.B...',
  '.BB...B...BB.',
  '.B..SSS..B...',
  '.B.B...B.B.B.',
  '...B.W.B.....',
  'BB...B...B.BB',
  '...SS...SS...',
  'BB.B...B...BB',
  '...B.W.B.....',
  '.B.B...B.B.B.',
  '.B..SSS..B...',
  '.BB..B..BB...',
  '.....BEB.....',
]

export const DEFAULT_PLAYER_SPAWN: Vec = {
  x: 4,
  y: 11,
}

export const DEFAULT_ENEMY_SPAWNS: Vec[] = [
  { x: 0, y: 0 },
  { x: 6, y: 0 },
  { x: 12, y: 0 },
]

export const CAMPAIGN_LEVELS: LevelDefinition[] = [
  {
    id: 1,
    name: 'Outer Blocks',
    briefing: 'A light probe enters the city. Learn the lanes and keep the eagle standing.',
    rows: DEFAULT_LEVEL_ROWS,
    playerSpawn: DEFAULT_PLAYER_SPAWN,
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 6,
    activeEnemyLimit: 2,
    spawnInterval: 3.2,
    roleWeights: { base_attacker: 0.64, hunter: 0.28, wall_breaker: 0.08 },
    armoredEnemyRatio: 0.08,
    rewards: { credits: 90, xp: 50, score: 450 },
  },
  {
    id: 2,
    name: 'River Split',
    briefing: 'Water divides the field. Expect hunters to slip through the side lanes.',
    rows: [
      '...B...B.....',
      '.BB.B.B.B.BB.',
      '.....W.W.....',
      'BBB..W.W..BBB',
      '.....W.W.....',
      '.B.B.....B.B.',
      '...SS.SSS....',
      '.B.B.....B.B.',
      '.....W.W.....',
      'BBB..W.W..BBB',
      '.....S.S.....',
      '.BB.....BB...',
      '.....BEB.....',
    ],
    playerSpawn: { x: 4, y: 11 },
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 8,
    activeEnemyLimit: 3,
    spawnInterval: 2.95,
    roleWeights: { base_attacker: 0.52, hunter: 0.36, wall_breaker: 0.12 },
    armoredEnemyRatio: 0.16,
    rewards: { credits: 105, xp: 60, score: 600 },
  },
  {
    id: 3,
    name: 'Brickworks',
    briefing: 'Dense brick walls slow both sides. Wall breakers will carve shortcuts.',
    rows: [
      '.B.B.B.B.B.B.',
      'B...B...B...B',
      '.BBB.B.B.BBB.',
      '.....S.S.....',
      'BBB.B...B.BBB',
      '...B.W.W.B...',
      '.S...B.B...S.',
      '...B.W.W.B...',
      'BBB.B...B.BBB',
      '.....S.S.....',
      '.BBB...BBB...',
      'B...B.B...B..',
      '.....BEB.....',
    ],
    playerSpawn: { x: 4, y: 11 },
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 10,
    activeEnemyLimit: 3,
    spawnInterval: 2.7,
    roleWeights: { base_attacker: 0.44, hunter: 0.3, wall_breaker: 0.26 },
    armoredEnemyRatio: 0.22,
    rewards: { credits: 120, xp: 75, score: 780 },
  },
  {
    id: 4,
    name: 'Crossfire Yard',
    briefing: 'Open firing lanes punish hesitation. Watch the center and guard the base.',
    rows: [
      '.....B.B.....',
      '.SS..B.B..SS.',
      '.....B.B.....',
      'BBB.......BBB',
      '...S.W.W.S...',
      '.............',
      'BB.B.S.S.B.BB',
      '.............',
      '...S.W.W.S...',
      'BBB.......BBB',
      '.....B.B.....',
      '.SS..B.B..SS.',
      '.....BEB.....',
    ],
    playerSpawn: { x: 4, y: 11 },
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 12,
    activeEnemyLimit: 4,
    spawnInterval: 2.45,
    roleWeights: { base_attacker: 0.38, hunter: 0.43, wall_breaker: 0.19 },
    armoredEnemyRatio: 0.28,
    rewards: { credits: 140, xp: 90, score: 950 },
  },
  {
    id: 5,
    name: 'Steel Teeth',
    briefing: 'Steel bunkers create blind corners. Enemies will use the gaps aggressively.',
    rows: [
      '..S.B.B.S....',
      '.B..S.S..B.B.',
      '...BS.SB.....',
      'BB...B...BBBB',
      '..S.W.W.S....',
      '....BBB......',
      '.SS.....SS...',
      '....BBB......',
      '..S.W.W.S....',
      'BBBB...B...BB',
      '.....S.SB....',
      '.B.B..B..B.B.',
      '.....BEB.....',
    ],
    playerSpawn: { x: 4, y: 11 },
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 14,
    activeEnemyLimit: 4,
    spawnInterval: 2.25,
    roleWeights: { base_attacker: 0.36, hunter: 0.42, wall_breaker: 0.22 },
    armoredEnemyRatio: 0.32,
    rewards: { credits: 165, xp: 110, score: 1120 },
  },
  {
    id: 6,
    name: 'Open Gate',
    briefing: 'The base approach is exposed. Prioritize attackers before they line up.',
    rows: [
      '...B.....B...',
      '.B.B.S.S.B.B.',
      '.....S.S.....',
      'BBB.......BBB',
      '...W.B.B.W...',
      '.B.........B.',
      '....SS.SS....',
      '.B.........B.',
      '...W.B.B.W...',
      'BBB.......BBB',
      '.......B.....',
      '.B...B...B...',
      '......E......',
    ],
    playerSpawn: { x: 5, y: 11 },
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 16,
    activeEnemyLimit: 4,
    spawnInterval: 2.1,
    roleWeights: { base_attacker: 0.44, hunter: 0.38, wall_breaker: 0.18 },
    armoredEnemyRatio: 0.36,
    rewards: { credits: 190, xp: 130, score: 1320 },
  },
  {
    id: 7,
    name: 'Hunter Net',
    briefing: 'Fast hunters pressure both flanks while breakers open the center.',
    rows: [
      '.B...S...B...',
      '...B.S.B...B.',
      'B....S....B..',
      '.BBBB.BBBB...',
      '.....W.W.....',
      'BB.........BB',
      '...SS.SSS....',
      'BB.........BB',
      '.....W.W.....',
      '.BBBB.BBBB...',
      'B....S....B..',
      '...B...B...B.',
      '.....BEB.....',
    ],
    playerSpawn: { x: 4, y: 11 },
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 18,
    activeEnemyLimit: 5,
    spawnInterval: 1.9,
    roleWeights: { base_attacker: 0.3, hunter: 0.5, wall_breaker: 0.2 },
    armoredEnemyRatio: 0.4,
    rewards: { credits: 225, xp: 155, score: 1600 },
  },
  {
    id: 8,
    name: 'Final Foundry',
    briefing: 'The last assault is heavy and direct. Hold the eagle through the full wave.',
    rows: [
      '..B.S.S.B....',
      '.B..S.S..B.B.',
      'B...B.B...B..',
      '...BBB.BBB...',
      '.S.W...W.S...',
      'BB...B...BB..',
      '...SS.SSS....',
      'BB...B...BB..',
      '.S.W...W.S...',
      '...BBB.BBB...',
      'B.....B...B..',
      '.B...B...B.B.',
      '......E......',
    ],
    playerSpawn: { x: 5, y: 11 },
    enemySpawns: DEFAULT_ENEMY_SPAWNS,
    enemyTotal: 20,
    activeEnemyLimit: 5,
    spawnInterval: 1.7,
    roleWeights: { base_attacker: 0.4, hunter: 0.34, wall_breaker: 0.26 },
    armoredEnemyRatio: 0.48,
    rewards: { credits: 280, xp: 205, score: 2200 },
  },
]

export function createTiles(rows = DEFAULT_LEVEL_ROWS): Tile[][] {
  if (rows.length !== GRID_ROWS) {
    throw new Error(`Level must contain ${GRID_ROWS} rows`)
  }

  return rows.map((row, rowIndex) => {
    if (row.length !== GRID_COLS) {
      throw new Error(`Level row ${rowIndex} must contain ${GRID_COLS} columns`)
    }

    return [...row].map(tileFromChar)
  })
}

function tileFromChar(char: string): Tile {
  const kindByChar: Record<string, TileKind> = {
    '.': 'empty',
    B: 'brick',
    S: 'steel',
    W: 'water',
    T: 'trees',
    E: 'base',
  }
  const kind = kindByChar[char] ?? 'empty'

  return {
    kind,
    hp: kind === 'brick' ? 2 : kind === 'base' ? 1 : 0,
  }
}
